"""programming is the writing of accurate step by step instructions that a computer can interprete and understand"""
"""Backend is where the main processing is done"""
"""The critical step is to add the phyton.exe to PATH"""
"""The three phyton extensions that we installed today are Phyton- code compiler, Pylance- code completer, Phyton indent- code correcter"""
"""using the vs code play button, using the vs code integrated terminal, using the system terminal"""
city=" New york"
"""My age is"""
#,"""
"""Git is an offline software, Github is an online based cloud"""
"""My backend journey with innovempia"""