"""save as creates duplicate files which can be lost but it is the opposite for git(commit)"""
"""git config --global user.name and git config --global user.email"""
"""Repositories are folders tracked by git on a local computer"""
"""git commit is to take a snapshot of the code but git push is to upload it """
"""Origin stands for the cloud server(GitHub)"""
"""git revert is  safe to use because it takes bad snapshots of your code and reverts them"""
"""git rebase can rewrite the history of the code causing choas"""
"""git checkout -b "new branch" """
"""cloning downloads a copy of the repository while forking creates a server side copy of the repository under your account"""
""" pull requests is a process of reviewing a code"""